[package]
name = "net_sentry"
version = "0.2.0"
edition = "2021"

[lib]
name = "net_sentry"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
pcap = "0.9"
